---
# tasks file for jpnewman.nginx

- name: ssl-certs group
  group: name=ssl-cert state=present
  become: yes
  tags: ssl

- name: Make sure nginx user is in ssl-cert
  user: name=nginx groups=www-data,ssl-cert
  become: yes
  tags: nginx

- name: Creating SSL certs CA directory
  file: path={{ ssl_ca_path | dirname }} mode=755 state=directory owner=root
  become: yes
  tags: ssl
  when: ssl_ca_path is defined and ssl_ca_path

- name: Creating SSL certs directory
  file: path={{ ssl_cert_path | dirname }} mode=755 state=directory owner=root
  become: yes
  tags: ssl
  when: ssl_cert_path is defined and ssl_cert_path

- name: Creating SSL private directory
  file: path={{ ssl_key_path | dirname }} mode=700 state=directory owner=root
  become: yes
  tags: ssl
  when: ssl_key_path is defined and ssl_key_path

- name: Copying SSL CA
  copy:
    src="{{ ssl_ca_local_path }}"
    dest="{{ ssl_ca_path }}"
    owner=0
    group=ssl-cert
    mode=0640
  tags: ssl
  when: ssl_ca_local_path is defined and ssl_ca_local_path

- name: Copying SSL cert
  copy:
    src="{{ ssl_cert_local_path }}"
    dest="{{ ssl_cert_path }}"
    owner=0
    group=0
    mode=0644
  tags: ssl
  when: ssl_cert_local_path is defined and ssl_cert_local_path
  notify: restart nginx

- name: Copying SSL key
  copy:
    src="{{ ssl_key_local_path }}"
    dest="{{ ssl_key_path }}"
    owner=0
    group=ssl-cert
    mode=0640
  tags: ssl
  when: ssl_key_local_path is defined and ssl_key_local_path
  notify: restart nginx

# Create vhost
- name: Add managed vhost config file
  template:
    src: "{{ nginx_template_file }}"
    dest: "{{ nginx_vhost_available_path }}/{{ nginx_vhost_filename }}.conf"
    mode: 0644
  tags: vhost
  when: nginx_template_file is defined
  notify: reload nginx

- name: Generate multiple nginx configurations
  include: templates.yml
  with_dict: "{{ nginx_vhosts_data | default({}) }}"
  notify: reload nginx

- name: Generate server_acls.conf
  template:
    src: server_acls.conf.j2
    dest: ./tmp/server_acls.conf
  when: nginx_acl_rules is defined

- name: Create symlink to nginx.conf
  file: src="{{ nginx_vhost_available_path }}/{{ nginx_vhost_filename }}.conf" dest="{{ nginx_vhost_path }}/{{ nginx_vhost_filename }}.conf" state=link
  tags: vhost
  notify: restart nginx

- name: Check nginx config
  become: yes
  command: service nginx configtest
  register: result
  changed_when: False

- name: Flush handlers
  meta: flush_handlers
